version: '3'
services:
  tornado-db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=items
      - MYSQL_USER=tornado
      - MYSQL_PASSWORD=strongpassword
      - MYSQL_ROOT_PASSWORD

  tornado-redis:
    image: redis
    command: >
     --requirepass tornadoapi

  tornado-apix:
    build: .
    image: jamtur01/tornado-apix-jaeger
    ports:
      - "3005:80"
    environment:
      - REDIS_URL=redis://redis/1
      - DB_HOSTNAME=db
    depends_on:
      - tornado-redis
      - tornado-db

  tornado-apiy:
    build: .
    image: jamtur01/tornado-apiy-jaeger
    ports:
      - "3006:80"
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - tornado-redis
      - tornado-db

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "3007:16686"
      - "9411:9411"
      - "9410:9410"
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
    depends_on:
      - tornado-apix
      - tornado-apiy
